# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This file is auto-generated by generate_components.py
# Each pet/nulls pair is uniquely named and references each other.

component "pet_1" {
  for_each = var.prefixes
  source = "./pet"

  inputs = {
    prefix = each.value
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_1" {
  for_each = component.pet_1

  source = "./nulls"

  inputs = {
    pet       = each.value.name
    instances = var.instances
  }

  providers = {
    null = provider.null.this
  }
}
