# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This file is auto-generated by generate_components.py
# Each pet/nulls pair is uniquely named and references each other.
variable "inputs" {
  type = map(object({
    prefix = string
    instances   = number
  }))
}

component "pet_1" {
  source = "./pet"

  inputs = {
    prefix = var.prefix
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_1" {
  source = "./nulls"

  inputs = {
    pet       = component.pet_1.name
    instances = 10
  }

  providers = {
    null = provider.null.this
  }
}
