# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This file is auto-generated by generate_components.py
# Each pet/nulls pair is uniquely named and references each other.

component "pet_1" {
  source = "./pet"

  inputs = {
    prefix = var.prefix
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_1" {
  source = "./nulls"

  inputs = {
    pet       = component.pet_1.name
    instances = 5
  }

  providers = {
    null = provider.null.this
  }
}

component "pet_2" {
  source = "./pet"

  inputs = {
    prefix = var.prefix
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_2" {
  source = "./nulls"

  inputs = {
    pet       = component.pet_2.name
    instances = 5
  }

  providers = {
    null = provider.null.this
  }
}

component "pet_3" {
  source = "./pet"

  inputs = {
    prefix = var.prefix
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_3" {
  source = "./nulls"

  inputs = {
    pet       = component.pet_3.name
    instances = 2
  }

  providers = {
    null = provider.null.this
  }
}

component "pet_4" {
  source = "./pet"

  inputs = {
    prefix = var.prefix
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_4" {
  source = "./nulls"

  inputs = {
    pet       = component.pet_4.name
    instances = 1
  }

  providers = {
    null = provider.null.this
  }
}

component "pet_5" {
  source = "./pet"

  inputs = {
    prefix = var.prefix
  }

  providers = {
    random = provider.random.this
  }
}

component "nulls_5" {
  source = "./nulls"

  inputs = {
    pet       = component.pet_5.name
    instances = 7
  }

  providers = {
    null = provider.null.this
  }
}
